export const GET_ALL_AUTHOR = 'GET_ALL_AUTHOR';
export const GET_ALL_AUTHOR_SAGA = 'GET_ALL_AUTHOR_SAGA';

export const CREATE_AUTHOR_SAGA = 'CREATE_AUTHOR';

export const DELETE_AUTHOR_SAGA = 'DELETE_AUTHOR_SAGA';

export const UPDATE_AUTHOR_SAGA = 'UPDATE_AUTHOR_SAGA';

export const GET_AUTHOR_SAGA = 'GET_AUTHOR_SAGA';