export const GET_ALL_BOOK = 'GET_ALL_BOOK';
export const GET_ALL_BOOK_SAGA = 'GET_ALL_BOOK_SAGA';

export const CREATE_BOOK_SAGA = 'CREATE_BOOK_SAGA';
export const CREATE_BOOK_CARD_SAGA = 'CREATE_BOOK_CARD_SAGA';
export const UPDATE_CODE_BOOK = 'UPDATE_CODE_BOOK';
export const UPDATE_BOOK_CARD = 'UPDATE_BOOK_CARD';
export const UPDATE_CODE_CARD = 'UPDATE_CODE_CARD';

export const ADD_BOOK_INTO_CARD_SAGA = 'ADD_BOOK_INTO_CARD_SAGA';

export const DELETE_BOOK_SAGA = 'DELETE_BOOK_SAGA';

export const UPDATE_BOOK_SAGA = 'UPDATE_BOOK_SAGA';
export const VIEW_BOOK_CARD_SAGA = 'VIEW_BOOK_CARD_SAGA';
export const GET_ALL_BOOK_CARD_BY_READER = 'GET_ALL_BOOK_CARD_BY_READER';
export const GET_ALL_BOOK_BY_FIEUSACH = 'GET_ALL_BOOK_BY_FIEUSACH';

export const VIEW_DETAILD_BOOK_CARD_SAGA = 'VIEW_DETAILD_BOOK_CARD_SAGA';

export const GET_BOOK_SAGA = 'GET_BOOK_SAGA';
export const GIVE_BOOK_BACK = 'GIVE_BOOK_BACK';
export const PREVIEW_GIVE_BOOK_SAGA = 'PREVIEW_GIVE_BOOK_SAGA';

