export const GET_ALL_BOOKSHELF = 'GET_ALL_BOOKSHELF';
export const GET_ALL_BOOKSHELF_SAGA = 'GET_ALL_BOOKSHELFbook_SAGA';

export const CREATE_BOOKSHELF_SAGA = 'CREATE_BOOKSHELF_SAGA';

export const DELETE_BOOKSHELF_SAGA = 'DELETE_BOOKSHELF_SAGA';

export const UPDATE_BOOKSHELF_SAGA = 'UPDATE_BOOKSHELF_SAGA';

export const GET_BOOKSHELF_SAGA = 'GET_BOOKSHELF_SAGA';

