export const GET_ALL_BOOK_BY_READER_SAGA = 'GET_ALL_BOOK_BY_READER_SAGA';
export const GET_ALL_BOOK_BY_READER = 'GET_ALL_BOOK_BY_READER';
export const GET_ALL_BOOK_BY_ACOUNT = 'GET_ALL_BOOK_BY_ACOUNT';


