export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SAGA = 'GET_ALL_CATEGORY_SAGA';

export const CREATE_CATEGORY_SAGA = 'CREATE_CATEGORY';

export const DELETE_CATEGORY_SAGA = 'DELETE_CATEGORY_SAGA';

export const UPDATE_CATEGORY_SAGA = 'UPDATE_CATEGORY_SAGA';

export const GET_CATEGORY_SAGA = 'GET_CATEGORY_SAGA';


