export const CREATE_FEEDBACK_SAGA = 'CREATE_FEEDBACK_SAGA';
export const GET_ALL_FEEDBACK = 'GET_ALL_FEEDBACK';

export const GET_ALL_FEEDBACK_SAGA = 'GET_ALL_FEEDBACK_SAGA';
export const UPDATE_TRANGTHAI_FEEDBACK_SAGA = 'UPDATE_TRANGTHAI_FEEDBACK_SAGA';
export const VIEW_FEEDBACK = 'VIEW_FEEDBACK';


