export const GET_ALL_MONEY_SAGA = 'GET_ALL_MONEY_SAGA';
export const GET_ALL_MONEY = 'GET_ALL_MONEY';
export const GET_ALL_MONEY_DETAILD_BY_READER = 'GET_ALL_MONEY_DETAILD_BY_READER';
export const GET_ALL_MONEY_DETAILD_BY_READER_SAGA = 'GET_ALL_MONEY_DETAILD_BY_READER_SAGA';


export const PAYMENT_SAGA = 'PAYMENT_SAGA';



