export const GET_ALL_PUBLISHER = 'GET_ALL_PUBLISHER';
export const GET_ALL_PUBLISHER_SAGA = 'GET_ALL_PUBLISHER_SAGA';

export const CREATE_PUBLISHER_SAGA = 'CREATE_PUBLISHER_SAGA';

export const DELETE_PUBLISHER_SAGA = 'DELETE_PUBLISHER_SAGA';

export const UPDATE_PUBLISHER_SAGA = 'UPDATE_PUBLISHER_SAGA';

export const GET_PUBLISHER = 'GET_PUBLISHER';
export const GET_PUBLISHER_SAGA = 'GET_PUBLISHER_SAGA';