export const GET_ALL_STAFF = 'GET_ALL_STAFF';
export const GET_ALL_STAFF_SAGA = 'GET_ALL_STAFF_SAGA';

export const CREATE_STAFF_SAGA = 'CREATE_STAFF_SAGA';

export const DELETE_STAFF_SAGA = 'DELETE_STAFF_SAGA';

export const UPDATE_STAFF_SAGA = 'UPDATE_STAFF_SAGA';
export const UPDATE_INFOR_STAFF = 'UPDATE_INFOR_STAFF';
export const UPDATE_STAFF_INFOR_SAGA = 'UPDATE_STAFF_INFOR_SAGA';

export const GET_STAFF = 'GET_STAFF';
export const GET_STAFF_SAGA = 'GET_STAFF_SAGA';
export const UPDATE_MA_THONG_TIN_CHUNG_STAFF = 'UPDATE_MA_THONG_TIN_CHUNG_STAFF';
